"use client";

import React from 'react';
import { motion } from "framer-motion";
import { ChatMessage } from '@/lib/types';


export const ChatMessages = ({ messages }: { messages: ChatMessage[] }) => {
    return (
        <>
            {messages.map((message, index) => (
                <motion.div
                    key={message.id}
                    id={message.id}
                    className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.1 * index }}
                >
                    <div className={`relative text-left bg-white/10 dark:bg-white/10 backdrop-blur-sm rounded-2xl p-4 shadow-lg mt-6 max-w-[85%] ${message.role === 'agent' ? 'rounded-tl-none' : 'rounded-tr-none'}`}>
                        <div className="relative z-10 text-gray-900 dark:text-white">
                            {message.content}
                            {message.role === 'agent' && (
                                <div className="text-[10px] text-gray-500 dark:text-gray-400 mt-2 text-right">
                                    ✨ Message generated by Leila's AI assistant ✨
                                </div>
                            )}
                        </div>
                    </div>
                </motion.div>
            ))}
        </>
    )
}